### ISSUE TITLE
[BUG] redhat-actions/oc-login using deprecated version of Node.js

### ISSUE THREAD

**Issue by nsalfos** [redhat-actions/oc-login#25]
### Version
redhat-actions/oc-login@v1.1.2

### Describe the bug

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: redhat-actions/openshift-tools-installer, redhat-actions/oc-login
`
### Steps to reproduce, workflow links, screenshots

Any attempt to use the actions should show this warning. 
I already reported in 2 other actions that apparently also used deprecated versions of Node.js. [here](https://github.com/tj-actions/changed-files/issues/678) & [here](https://github.com/mxschmitt/action-tmate/issues/139)

**Comment by smlgbl** [comment]
I created PR #26 for this.

**Comment by ssuganth** [comment]
@smlgbl - Do you know who needs to approve this PR to get merged?

**Comment by ssuganth** [comment]
@tetchel @divyansh42 - Can someone pls look into this issue?

**Comment by smlgbl** [comment]
> @smlgbl - Do you know who needs to approve this PR to get merged?

No, sorry. Maybe redhat doesn't care :(

**Comment by chrispoupart** [comment]
Was really hoping to see this resolved by now as well.

Speak to your Red Hat reps and ask them to help bring it to the maintainer's attention.

**Comment by smlgbl** [comment]
PR #26 has been merged! Yay!

**Comment by divyansh42** [comment]
Action has been updated to use Node16
