### ISSUE TITLE
[BUG] redhat-actions/oc-login using deprecated version of Node.js

### ISSUE THREAD

**Issue by sepulvedablanco** [redhat-actions/oc-login#35]
### Version

redhat-actions/oc-login@v1.2

### Describe the bug

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: redhat-actions/oc-login@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
 
### Steps to reproduce, workflow links, screenshots

Any attempt to use the actions should show this warning.

**Comment by sepulvedablanco** [comment]
@divyansh42 ^^

**Comment by sepulvedablanco-inditex** [comment]
@tetchel @smlgbl can you review the issue & linked PR?

**Comment by sepulvedablanco** [comment]
@tetchel @smlgbl can you review the issue & linked PR?

**Comment by smlgbl** [comment]
I'm not a maintainer, but you got my support & approval :)

**Comment by sepulvedablanco-inditex** [comment]
@divyansh42 please :)

**Comment by sepulvedablanco** [comment]
@divyansh42 can you take a look, please?

**Comment by divyansh42** [comment]
Hello @sepulvedablanco we will look at it soon.

**Comment by sepulvedablanco** [comment]
@divyansh42  any news?

**Comment by sepulvedablanco** [comment]
@divyansh42 friendly reminder 😅

**Comment by sepulvedablanco** [comment]
@divyansh42  please

**Comment by divyansh42** [comment]
@sepulvedablanco due to multiple other priorities we were not able to prioritise it. I will make sure to look at it very soon.
Apologies for the delay.

**Comment by divyansh42** [comment]
Fix has been released with version `v1.3` and `v1`
